version: 2.1

jobs:
  build_atmega2560_firmware:
    docker:
      - image: jimmykzm94/avr-toolchain-amd64:15.2.0
    steps:
      - checkout
      - run:
          name: Build ATmega Firmware
          command: make -f crossfirmarizer/crossfirmarizer_ATmega2560.mk all
      - store_artifacts:
          path: .  # Adjust to your specific hex output folder if needed
          destination: outputs/atmega2560

  build_python:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Build Python Package
          command: |
            pip install build
            python -m build crossfirmarizer_client_python
      - store_artifacts:
          path: dist
          destination: outputs/python

workflows:
  build-and-package:
    jobs:
      - build_atmega2560_firmware
      - build_python