version: 2.1

jobs:
  prebuild_set_build_version:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - run:
          name: Set Build Version
          command: python circleci_set_version.py
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  build_atmega2560_firmware:
    docker:
      - image: jimmykzm94/avr-toolchain-amd64:15.2.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build ATmega Firmware
          command: make -f crossfirmarizer/crossfirmarizer_ATmega2560.mk all
      - persist_to_workspace:
          root: .
          paths:
            - crossfirmarizer/build/crossfirmarizer_ATmega2560.hex

  build_python:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build Python Package
          command: |
            pip install build
            python -m build crossfirmarizer_client_python
      - persist_to_workspace:
          root: .
          paths:
            - crossfirmarizer_client_python/dist

  collect_artifacts:
    docker:
      - image: cimg/base:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Collect Artifacts
          command: |
            mkdir -p collected_artifacts
            cp crossfirmarizer/build/crossfirmarizer_ATmega2560.hex collected_artifacts/
            cp -r crossfirmarizer_client_python/dist/* collected_artifacts/
      - store_artifacts:
          path: collected_artifacts
          destination: .

workflows:
  build-and-package:
    jobs:
      - prebuild_set_build_version:
          filters:
            branches:
              only: /^release\/.*/
      - collect_artifacts:
          requires:
            - build_atmega2560_firmware
            - build_python
          filters:
            branches:
              only: /^release\/.*/
      - build_atmega2560_firmware:
          requires:
            - prebuild_set_build_version
          filters:
            branches:
              only: /^release\/.*/
      - build_python:
          requires:
            - prebuild_set_build_version
          filters:
            branches:
              only: /^release\/.*/