#include "pins.h"
#include <stddef.h>

#ifdef TARGET_ATMEGA2560

const pin_map_t pins[PIN_MAX_COUNT] = {
    // Arduino Analog Pins (A0-A15)
    [A0] = {&PORTF, &DDRF, &PINF, 0},
    [A1] = {&PORTF, &DDRF, &PINF, 1},
    [A2] = {&PORTF, &DDRF, &PINF, 2},
    [A3] = {&PORTF, &DDRF, &PINF, 3},
    [A4] = {&PORTF, &DDRF, &PINF, 4},
    [A5] = {&PORTF, &DDRF, &PINF, 5},
    [A6] = {&PORTF, &DDRF, &PINF, 6},
    [A7] = {&PORTF, &DDRF, &PINF, 7},
    [A8] = {&PORTK, &DDRK, &PINK, 0},
    [A9] = {&PORTK, &DDRK, &PINK, 1},
    [A10] = {&PORTK, &DDRK, &PINK, 2},
    [A11] = {&PORTK, &DDRK, &PINK, 3},
    [A12] = {&PORTK, &DDRK, &PINK, 4},
    [A13] = {&PORTK, &DDRK, &PINK, 5},
    [A14] = {&PORTK, &DDRK, &PINK, 6},
    [A15] = {&PORTK, &DDRK, &PINK, 7},

    // Arduino Digital Pins (D0-D53)
    [D0] = {&PORTE, &DDRE, &PINE, 0},
    [D1] = {&PORTE, &DDRE, &PINE, 1},
    [D2] = {&PORTE, &DDRE, &PINE, 4},
    [D3] = {&PORTE, &DDRE, &PINE, 5},
    [D4] = {&PORTG, &DDRG, &PING, 5},
    [D5] = {&PORTE, &DDRE, &PINE, 3},
    [D6] = {&PORTH, &DDRH, &PINH, 3},
    [D7] = {&PORTH, &DDRH, &PINH, 4},
    [D8] = {&PORTH, &DDRH, &PINH, 5},
    [D9] = {&PORTH, &DDRH, &PINH, 6},
    [D10] = {&PORTB, &DDRB, &PINB, 4},
    [D11] = {&PORTB, &DDRB, &PINB, 5},
    [D12] = {&PORTB, &DDRB, &PINB, 6},
    [D13] = {&PORTB, &DDRB, &PINB, 7},
    [D14] = {&PORTJ, &DDRJ, &PINJ, 1},
    [D15] = {&PORTJ, &DDRJ, &PINJ, 0},
    [D16] = {&PORTH, &DDRH, &PINH, 1},
    [D17] = {&PORTH, &DDRH, &PINH, 0},
    [D18] = {&PORTD, &DDRD, &PIND, 3},
    [D19] = {&PORTD, &DDRD, &PIND, 2},
    [D20] = {&PORTD, &DDRD, &PIND, 1},
    [D21] = {&PORTD, &DDRD, &PIND, 0},
    [D22] = {&PORTA, &DDRA, &PINA, 0},
    [D23] = {&PORTA, &DDRA, &PINA, 1},
    [D24] = {&PORTA, &DDRA, &PINA, 2},
    [D25] = {&PORTA, &DDRA, &PINA, 3},
    [D26] = {&PORTA, &DDRA, &PINA, 4},
    [D27] = {&PORTA, &DDRA, &PINA, 5},
    [D28] = {&PORTA, &DDRA, &PINA, 6},
    [D29] = {&PORTA, &DDRA, &PINA, 7},
    [D30] = {&PORTC, &DDRC, &PINC, 7},
    [D31] = {&PORTC, &DDRC, &PINC, 6},
    [D32] = {&PORTC, &DDRC, &PINC, 5},
    [D33] = {&PORTC, &DDRC, &PINC, 4},
    [D34] = {&PORTC, &DDRC, &PINC, 3},
    [D35] = {&PORTC, &DDRC, &PINC, 2},
    [D36] = {&PORTC, &DDRC, &PINC, 1},
    [D37] = {&PORTC, &DDRC, &PINC, 0},
    [D38] = {&PORTD, &DDRD, &PIND, 7},
    [D39] = {&PORTG, &DDRG, &PING, 2},
    [D40] = {&PORTG, &DDRG, &PING, 1},
    [D41] = {&PORTG, &DDRG, &PING, 0},
    [D42] = {&PORTL, &DDRL, &PINL, 7},
    [D43] = {&PORTL, &DDRL, &PINL, 6},
    [D44] = {&PORTL, &DDRL, &PINL, 5},
    [D45] = {&PORTL, &DDRL, &PINL, 4},
    [D46] = {&PORTL, &DDRL, &PINL, 3},
    [D47] = {&PORTL, &DDRL, &PINL, 2},
    [D48] = {&PORTL, &DDRL, &PINL, 1},
    [D49] = {&PORTL, &DDRL, &PINL, 0},
    [D50] = {&PORTB, &DDRB, &PINB, 3},
    [D51] = {&PORTB, &DDRB, &PINB, 2},
    [D52] = {&PORTB, &DDRB, &PINB, 1},
    [D53] = {&PORTB, &DDRB, &PINB, 0},

    // Helpful pins
    [PIN_LED] = {&PORTB, &DDRB, &PINB, 7} // Onboard LED on D13 (PB7)
};

#endif